# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e580c9ced129d3b8544cbf9d612420c37e93a20f489ecc75908bb9487b6c8120ea4fc32c7703716329203395f7600b36f264d1d03244f2cf9e8e50c8f74c5d

test:
  secret_key_base: 60d17cc667879502eac2ede1b128e2b6a109d3cc72057a735b836580953f8197e150ed33c6a00f412ed77893c4e33df260ac5a669aef3ff26e93b5dd6205f241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
