# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b89ba940cdc661f9c666ca1892163fdbe04280b4c945297f053864d8b152e065587954e4ff7b2e073bb34df56d9c6d9cee427fb670f6f415f196429a49e68489

test:
  secret_key_base: 66752df18382925f272d50c065599b8657ead4bd6a63e1957d5b8f73efb2ff7d2c455e69f6ac260c4ebd33f78590b5d1d19bc0f8f2eaf3698d08900b1402011c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
