# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a420041757ceec49648a8fba849201701559eb29bdd67632804e5b293377b1f2c547852115602891b63bd95139c1233c1d3310affac924b35e32b02deeea4471

test:
  secret_key_base: 35fe4e4043cd5438e229fda800f38da0fec65b0d9d9f841f38f6628a08eacaa8c34764027f31b29319dc942d0ac202f374b392c73eac9242518164ea29033534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
